### ISSUE TITLE
Would this approach also work for Metabase?

### ISSUE THREAD

**Issue by abdel-87** [slidoapp/dbt-superset-lineage#10]
Hi,

thank you for the great package. would something like this also work with Metabase?

Thank you

**Comment by mrshu** [comment]
Hi @abdel-87,

I am afraid we do not really have much experience with Metabase, but assuming it does have a similar API, I don't really see why it should not -- the whole approach is rather general 🙂

**Comment by one-data-cookie** [comment]
@abdel-87 I believe [`dbt-metabase`](https://github.com/gouline/dbt-metabase) might be what you are after. 😉
