### ISSUE TITLE
Update needed on sqlfluff version

### ISSUE THREAD

**Issue by MuslimBeibytuly** [slidoapp/dbt-superset-lineage#11]
Because dbt-superset-lineage (0.2.1) depends on sqlfluff (>=0.8.2,<0.9.0)
 and no versions of dbt-superset-lineage match >0.2.1,<0.3.0, dbt-superset-lineage (>=0.2.1,<0.3.0) requires sqlfluff (>=0.8.2,<0.9.0).
So, because seed depends on both dbt-superset-lineage (^0.2.1) and sqlfluff (^1.4.1), version solving failed.

**Comment by MuslimBeibytuly** [comment]
@one-data-cookie @mrshu @sweco could you review and merge it?

**Comment by mrshu** [comment]
@MuslimBeibytuly Just out of curiosity, was the sqlfluff already present in your environment when you tried to install `dbt-superset-lineage`?

**Comment by MuslimBeibytuly** [comment]
@mrshu yup,sqlfluff with higher version was already there
