### ISSUE TITLE
Referenced SQLFluff Version is Still 1.4.5

### ISSUE THREAD

**Issue by bkimjin** [slidoapp/dbt-superset-lineage#33]
https://github.com/slidoapp/dbt-superset-lineage/pull/32 states that SQLFluff should have been updated to 2.1.2, but it seems like dbt-superset-lineage is still referencing 1.4.5.

## Commands On a Clean Virtual Instance
pip list
```
Package    Version
---------- -------
pip        22.3.1
setuptools 68.0.0
wheel      0.38.4
```
pipenv install dbt-superset-lineage
```
Package              Version
-------------------- ---------
...
setuptools           68.0.0
soupsieve            2.4.1
sqlfluff             1.4.5
tblib                2.0.0
toml                 0.10.2
...
```

**Comment by one-data-cookie** [comment]
@bkimjin Thanks for raising this! I haven't released `v0.3.3` that would include #32. Let me do that next week.

**Comment by bkimjin** [comment]
@one-data-cookie do you know what the timeline is for `v0.3.3`?

**Comment by one-data-cookie** [comment]
@bkimjin Thanks for the ping! It's now [released](https://github.com/slidoapp/dbt-superset-lineage/commit/88575bbd1b5473c1d0525a21cc4bfb60bf7628c0). 😉
