### ISSUE TITLE
Pull dashboards has old API calls

### ISSUE THREAD

**Issue by agusfigueroa-htg** [slidoapp/dbt-superset-lineage#9]
Hey guys,
I adapted the pull_dashboards.py file to use it as, when trying to run the code out of the box, I was not getting the dashboards' table names. 

Out of my interpretation `GET /dashboard/id` doesn't return "table_name" anymore and it was replaced by a similar command I found (`GET /dashboard/id/datasets`).

Let me know how this sounds to you, I am happy to contribute with my minor edits.
Best,
Agus

**Comment by one-data-cookie** [comment]
@agusfigueroa-htg I just released `v0.3.0` that [implements your suggestion](https://github.com/slidoapp/dbt-superset-lineage/pull/22/files#diff-f64cb869671114f2b4ecc7a6c9b1b133b9d02fb79656b1701856e7d96fbc60acR128) apart from [quite a few other things](https://github.com/slidoapp/dbt-superset-lineage/compare/v0.2.1...v0.3.0).

Apologies this took a while to address! 🙈
